# Generated by Django 5.0.4 on 2024-04-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Developer')),
                ('name', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.TextField(max_length=255)),
                ('slug', models.SlugField(max_length=15)),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.developer')),
            ],
        ),
    ]
