# Generated by Django 5.0.4 on 2024-04-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.developer', to_field='name'),
        ),
    ]
